  CREATE TABLE "TCH_FUNC_PROGRESS_TEXTS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"FUNCTION_NAME" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"PROGRESS_TEXT" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"LANG" VARCHAR2(32) COLLATE "USING_NLS_COMP", 
	"CREATED" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"UPDATED" DATE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	 CONSTRAINT "TCH_FUNC_PROGRESS_TEXTS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "TCH_FUNC_PROGRESS_TEXTS_UNIQ1" UNIQUE ("FUNCTION_NAME", "LANG")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

  CREATE INDEX "TCH_FUNC_PROGRESS_TEXTS_I1" ON "TCH_FUNC_PROGRESS_TEXTS" ("FUNCTION_NAME");
  CREATE SEQUENCE TCH_FUNC_PROGRESS_TEXTS_ID_SEQ minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 1 nocache noorder nocycle nokeep noscale global;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TCH_FUNC_PROGRESS_TEXTS_BIU" 
    before insert or update   
    on TCH_FUNC_PROGRESS_TEXTS  
    for each row  
begin  
    if(updating or inserting) and :new.ID is null
    then
      :new.ID := TCH_FUNC_PROGRESS_TEXTS_ID_SEQ.nextval;
    end if;

    if inserting then  
        :new.created := sysdate;  
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);  
    end if;  
    :new.updated := sysdate;  
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);  
end TCH_FUNC_PROGRESS_TEXTS_BIU;
/
ALTER TRIGGER "TCH_FUNC_PROGRESS_TEXTS_BIU" ENABLE;