  CREATE TABLE "TCH_CHAT_MESSAGE" 
   (	"ID" NUMBER DEFAULT ON NULL to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') NOT NULL ENABLE, 
	"CHAT_SESSION_ID" NUMBER, 
	"SEQUENCE_NR" NUMBER, 
	"PROMPT_NR" NUMBER, 
	"MESSAGE_TYPE" VARCHAR2(80) COLLATE "USING_NLS_COMP", 
	"MESSAGE_TIMESTAMP" DATE, 
	"MESSAGE" CLOB COLLATE "USING_NLS_COMP", 
	"CREATED" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"UPDATED" DATE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"PROMPT_TOKENS" NUMBER, 
	"COMPLETION_TOKENS" NUMBER, 
	"TOTAL_TOKENS" NUMBER, 
	"MODEL" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
  "TECHNICAL_MESSAGE_KNZ" VARCHAR2(1) DEFAULT ON NULL 'N' NOT NULL,
  "FUNCTION_NAME" varchar2(255),
  "TOOLS_CALL_ID" varchar2(255),
  "ARGUMENTS" clob,
  "TYPE" varchar2(255),
  
	 CONSTRAINT "TCH_CHAT_MESSAGE_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

  ALTER TABLE "TCH_CHAT_MESSAGE" ADD CONSTRAINT "TCH_CHAT_MESS_CHAT_SESSION_FK" FOREIGN KEY ("CHAT_SESSION_ID")
	  REFERENCES "TCH_CHAT_SESSION" ("ID") ON DELETE CASCADE ENABLE;

  CREATE INDEX "TCH_CHAT_MESSAGE_I1" ON "TCH_CHAT_MESSAGE" ("CHAT_SESSION_ID") 
  ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TCH_CHAT_MESSAGE_BIU" 
    before insert or update   
    on tch_chat_message  
    for each row  
begin  
    if inserting then  
        :new.created := sysdate;  
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);  
    end if;  
    :new.updated := sysdate;  
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);  
end tch_chat_message_biu;  
 

/
ALTER TRIGGER "TCH_CHAT_MESSAGE_BIU" ENABLE;

--updates 17.11.2023
alter table TCH_CHAT_MESSAGE add TECHNICAL_MESSAGE_KNZ VARCHAR2(1) DEFAULT ON NULL 'N' NOT NULL ENABLE;
alter table TCH_CHAT_MESSAGE add constraint TCH_CHAT_MESSAGE_CHK_TECH check (TECHNICAL_MESSAGE_KNZ in ('Y','N'));

alter table TCH_CHAT_MESSAGE add "FUNCTION_NAME" varchar2(255);

--updates 01.12.2023
alter table TCH_CHAT_MESSAGE add "TOOLS_CALL_ID" varchar2(255);
alter table TCH_CHAT_MESSAGE add "ARGUMENTS" clob;
alter table TCH_CHAT_MESSAGE add "TYPE" varchar2(255);


